apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://raw.githubusercontent.com/longhorn/longhorn/v1.6.2/deploy/longhorn.yaml
- https://raw.githubusercontent.com/longhorn/longhorn/v1.6.2/examples/network-policy/backing-image-data-source-network-policy.yaml
- https://raw.githubusercontent.com/longhorn/longhorn/v1.6.2/examples/network-policy/backing-image-manager-network-policy.yaml
- https://raw.githubusercontent.com/longhorn/longhorn/v1.6.2/examples/network-policy/instance-manager-networking.yaml
- https://raw.githubusercontent.com/longhorn/longhorn/v1.6.2/examples/network-policy/manager-network-policy.yaml
- https://raw.githubusercontent.com/longhorn/longhorn/v1.6.2/examples/network-policy/recovery-backend-network-policy.yaml
- https://raw.githubusercontent.com/longhorn/longhorn/v1.6.2/examples/network-policy/webhook-network-policy.yaml
- snapshot.yaml
- network-policies.yaml
- Kptfile
- resourcegroup.yaml
patches:
- path: longhorn.yaml
generatorOptions:
  disableNameSuffixHash: true
