apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- apiserver.yaml
- cert-manager-solver.yaml
- dns.yaml
- internet-egress.yaml
- kube-system.yaml
- Kptfile
- resourcegroup.yaml
